spring.application.name=ms-products

# Mongo: usa variables de entorno y, si no existen, el contenedor local Lab_3
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGO_DB:products_db}